products/urls.py
from django.conf.urls import url
import views
from products.views import ProductAutocomplete


urlpatterns = [
	url(r'^product-autocomplete/$',ProductAutocomplete.as_view(),name='product_autocomplete'),
	url(r'^create/$', views.create, name="create"),
	url(r'^edit/(?P<pk>.*)/$', views.edit, name="edit"),
	url(r'^$', views.products, name="products"),
	url(r'^product/(?P<pk>.*)/$', views.product, name="product"),
	url(r'^delete/(?P<pk>.*)/$', views.delete, name="delete"),
	url(r'^get-product/$', views.get_product, name="get_product"),
]

sales/urls.py
from django.conf.urls import url
import views


urlpatterns = [
	url(r'^create/$', views.create, name="create"),
	url(r'^edit/(?P<pk>.*)/$', views.edit, name="edit"),
	url(r'^$', views.sales, name="sales"),
	url(r'^sale/(?P<pk>.*)/$', views.sale, name="sale"),
	url(r'^delete/(?P<pk>.*)/$', views.delete, name="delete"),
]

tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^api/v1/customers/', include('api.v1.customers.urls', namespace='api_v1_customers')),
    url(r'^api/v1/sales/', include('api.v1.sales.urls', namespace='api_v1_sales')),
    url(r'^api/v1/auth/', include('api.v1.authentication.urls', namespace='api_v1_authentication')),

    url(r'^$',general_views.app,name='app'),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),

    url(r'^app/customers/', include('customers.urls', namespace="customers")),
    url(r'^app/products/', include('products.urls', namespace="products")),
    url(r'^app/sales/', include('sales.urls', namespace="sales")),
    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^app/users/', include('users.urls', namespace="users")),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

products/models.py
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.core.validators import MinValueValidator
from decimal import Decimal
from main.models import BaseModel


class Product(BaseModel):
    name = models.CharField(max_length=128)
    price = models.DecimalField(default=0.00, decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])
    cost = models.DecimalField(default=0.00, decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])
    stock = models.DecimalField(default=0.00, decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])

    class Meta:
        db_table = 'products_product'
        verbose_name = '_(product)'
        verbose_name_plural = '_(products)'
        ordering = ('-date_added', 'name')

    def __unicode__(self):
        return str(self.name)

products/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.forms.widgets import TextInput, Textarea, Select
from products.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['auto_id', 'creator', 'updator', 'is_deleted']
        widgets = {
            'name': TextInput(attrs={'class': 'required form-control', 'placeholder': 'Name'}),
            'price': TextInput(attrs={'class': 'required form-control', 'placeholder': 'Price'}),
            'cost': TextInput(attrs={'class': 'form-control', 'placeholder': 'Cost'}),
            'stock': Textarea(attrs={'class': 'form-control', 'placeholder': 'Stock'})

        }
        error_messages = {
            'name' : {
                'required' : _("Name field is required."),
            },
            'price' : {
                'required' : _("Price field is required."),
            },
            'cost' : {
                'required' : _("Cost field is required."),
            },
            'stock' : {
                'required' : _("Stock field is required."),
            }
        }


        

products/views.py
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect, HttpResponse
from main.functions import get_auto_id, get_a_id, generate_form_errors
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import json
import datetime
from products.models import Product
from products.forms import ProductForm
from dal import autocomplete


class ProductAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        if not self.request.user.is_authenticated:
            return Product.objects.none()

        items = Product.objects.filter(is_deleted=False)

        if self.q:
            query = self.q
            items = items.filter(Q(name__icontains=query))

        return items


@login_required
def create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.creator = request.user
            data.updator = request.user
            data.auto_id = get_auto_id(Product)
            data.save()

            response_data = {
                'status': 'true',
                'title': 'Successfully Created',
                'message': 'Product Successfully Created',
                'redirect': 'true',
                'redirect_url': reverse('products:product', kwargs={"pk": data.pk})
            }
        else:
            message = generate_form_errors(form, formset=False)

            response_data = {
                'Status': 'false',
                'stable': 'true',
                'title': 'Form Validation Error',
                'message': message
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        form = ProductForm()
        context = {
            'form': form,
            'title': 'Create Product',
            'redirect': True,
            'url': reverse('products:create'),

            "is_need_select_picker" : True,
            "is_need_popup_box" : True,
            "is_need_custom_scroll_bar" : True,
            "is_need_wave_effect" : True,
            "is_need_bootstrap_growl" : True,
            "is_need_chosen_select" : True,
            "is_need_grid_system" : True,
            "is_need_datetime_picker" : True,
            "is_need_animations": True,
            "is_dashboard" :True
        }
        return render(request, 'products/entry.html', context)
        

@login_required
def edit(request, pk):
    instance = get_object_or_404(Product.objects.filter(pk=pk))
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=instance)
        if form.is_valid():
            data = form.save(commit=False)
            data.updator = request.user
            data.date_updated = datetime.datetime.now()
            data.save()

            response_data = {
                'status': 'true',
                'title': 'Successfully Updated',
                'message': 'Product Successfully Updated',
                'redirect': 'true',
                'redirect_url': reverse('products:product', kwargs={"pk": data.pk})
            }
        else:
            message = generate_form_errors(form, formset=False)

            response_data = {
                'Status': 'false',
                'stable': 'true',
                'title': 'Form Validation Error',
                'message': message
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        form = ProductForm(instance=instance)
        context = {
            'form': form,
            'title': 'Edit Product',
            'redirect': True,
            'url': reverse('products:edit', kwargs={'pk':instance.pk}),

            "is_need_select_picker" : True,
            "is_need_popup_box" : True,
            "is_need_custom_scroll_bar" : True,
            "is_need_wave_effect" : True,
            "is_need_bootstrap_growl" : True,
            "is_need_chosen_select" : True,
            "is_need_grid_system" : True,
            "is_need_datetime_picker" : True,
            "is_need_animations": True,
            "is_dashboard" :True
        }
        return render(request, 'products/entry.html', context)


@login_required
def products(request):
    instances = Product.objects.filter(is_deleted=False)
    context = {
        'title': 'Products',
        'instances': instances,

        "is_need_select_picker" : True,
        "is_need_popup_box" : True,
        "is_need_custom_scroll_bar" : True,
        "is_need_wave_effect" : True,
        "is_need_bootstrap_growl" : True,
        "is_need_chosen_select" : True,
        "is_need_grid_system" : True,
        "is_need_datetime_picker" : True,
        "is_need_animations": True,
        "is_dashboard" :True
    }
    return render(request, 'products/products.html', context)


@login_required
def product(request, pk):
    instance = get_object_or_404(Product.objects.filter(pk=pk))
    context = {
        'title': 'Product' + instance.name,
        'instance': instance,

        "is_need_select_picker" : True,
        "is_need_popup_box" : True,
        "is_need_custom_scroll_bar" : True,
        "is_need_wave_effect" : True,
        "is_need_bootstrap_growl" : True,
        "is_need_chosen_select" : True,
        "is_need_grid_system" : True,
        "is_need_datetime_picker" : True,
        "is_need_animations": True,
        "is_dashboard" :True
    }
    return render(request, 'products/product.html', context)


@login_required
def delete(request, pk):
    Product.objects.filter(pk=pk).update(is_deleted=True)
    response_data = {
        "status" : "true",
        "title" : "Successfully Deleted",
        "message" : "Product Successfully Deleted.",
        "redirect" : "true",
        "redirect_url" : reverse('customers:customers')
    }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


def get_product(request):
    pk = request.GET.get('id')
    if Product.objects.filter(pk=pk).exists():
        product = Product.objects.get(pk=pk)

        response_data = {
            'status': 'true',
            'stock': str(product.stock),
            'pk': str(product.pk)
        }
    else:
        response_data = {
            'status': 'false',
            'message': 'Product not exist'
        }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')

templates/products/entry.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
	<section id="content">
        <div class="container">
            <div class="c-header">
                <h2>{{title}}</h2>
            </div>

			<div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{title}}</div>

                <div class="ah-search">
	            	<form method="get" action="{% url 'products:products' %}">
	                    <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

	                    <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
	                    <input type="submit" class="hidden" />
	                </form>
	            </div>

                <ul class="ah-actions actions a-alt">
                    <li>
                        <a title="Search" data-ma-action="ah-search-open" class="ah-search-trigger" href="">
                            <i class="zmdi zmdi-search"></i>
                        </a>
                    </li>
                    {% if instance %}
                    <li>
                        <a title="Create Product" href="{% url 'products:create' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
                    <li>
                        <a title="View Product" href="{% url 'products:product' pk=instance.pk %}">
                            <i class="zmdi zmdi-eye"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Delete Product" data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'products:delete' pk=instance.pk %}" class="action-button redirect">
                            <i class="zmdi zmdi-delete"></i>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>

            <div class="card">
                <form class="ajax reset {% if redirect %}redirect{% endif %}" method="post" action="{{url}}">
                    	{% csrf_token %}
                        <div class="card-body card-padding">
                            <div class="row">
                                <div class="col-sm-6">
                                	{{ form.shop }}
                                    <div class="form-group fg-line">
    	                                <label for="{{ form.name.id_for_label }}">
    	                                	{{ form.name.label }}
    	                                	{% if form.name.field.required %}
    							        		<small class="star">*</small>
    							        	{% endif %}

    							        	{% if form.name.help_text %}
    							        		<span data-original-title="Field Info" title="" data-content="{{ form.name.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline">
    	                                    {% endif %}
    	                                </label>
    	                                {{ form.name }}

    	                                {% if form.name.errors %}
    	                                	<label class="error">{{ form.name.errors.as_text }}</label>
    	                                {% endif %}
    	                            </div>

                                    <div class="form-group fg-line">
                                        <label for="{{ form.price.id_for_label }}">
                                        	{{ form.price.label }}
                                        	{% if form.price.field.required %}
        						        		<small class="star">*</small>
        						        	{% endif %}

        						        	{% if form.price.help_text %}
        						        		<span data-original-title="Field Info" title="" data-content="{{ form.price.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline">
                                            {% endif %}
                                        </label>
                                        {{ form.price }}

                                        {% if form.price.errors %}
                                        	<label class="error">{{ form.price.errors.as_text }}</label>
                                        {% endif %}
                                    </div>

                                    <div class="form-group fg-line">
                                        <label for="{{ form.cost.id_for_label }}">
                                            {{ form.cost.label }}
                                            {% if form.cost.field.required %}
                                                <small class="star">*</small>
                                            {% endif %}

                                            {% if form.cost.help_text %}
                                                <span data-original-title="Field Info" title="" data-content="{{ form.cost.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline">
                                            {% endif %}
                                        </label>
                                        {{ form.cost }}

                                        {% if form.cost.errors %}
                                            <label class="error">{{ form.cost.errors.as_text }}</label>
                                        {% endif %}
                                    </div>

                                    <div class="form-group fg-line m-b-0">
                                        <label for="{{ form.stock.id_for_label }}">
                                            {{ form.stock.label }}
                                            {% if form.stock.field.required %}
                                                <small class="star">*</small>
                                            {% endif %}

                                            {% if form.stock.help_text %}
                                                <span data-original-title="Field Info" title="" data-content="{{ form.stock.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline">
                                            {% endif %}
                                        </label>
                                        {{ form.stock }}

                                        {% if form.stock.errors %}
                                            <label class="error">{{ form.stock.errors.as_text }}</label>
                                        {% endif %}
                                    </div>
                   
                                </div>

                                </div>
                            </div>
                    </div>
                <div>
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

{% block static %}
	{% load static %}
	<script type="text/javascript">
		$(document).ready(function(){
			$('input[type=text]').focus(function () {
	        $(this).select();
	    		});
		  });
	</script>
{% endblock %}

templates/products/product.html
{% extends "base.html" %}
{% load i18n %}

{% load users_template_tags %}
{% load tz %}
{% block content %}
	<section id="content">
        <div class="container">
            <div class="c-header">
                <h2>{{title}}</h2>
            </div>

            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{instance.name}} - {{instance.price}}</div>

                <ul class="ah-actions actions a-alt">
                    <li>
                        <a title="Create Product" href="{% url 'products:create' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Edit Product" href="{% url 'products:edit' pk=instance.pk %}">
                            <i class="zmdi zmdi-edit"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Delete Product" data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'products:delete' pk=instance.pk %}" class="action-button redirect">
                            <i class="zmdi zmdi-delete"></i>
                        </a>
                    </li>
                </ul>
            </div>

            <div id="c-grid" class="clearfix" data-columns="2">
                <div class="card">
                    <div class="card-header">
                        <h2>Basic Info <small></small></h2>
                    </div>

                    <div class="card-body">
                        <div class="list-group lg-alt c-overflow">
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Name</div>
                                    <small class="lgi-text">{{instance.name}}</small>
                                </div>
                            </div>

                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Price</div>
                                    <small class="lgi-text">{{instance.price}}</small>
                                </div>
                            </div>


                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Cost</div>
                                    <small class="lgi-text">{{instance.cost}}</small>
                                </div>
                            </div>
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Stock</div>
                                    <small class="lgi-text">{{instance.stock}}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

             </div>
    </section>
{% endblock %}

{% block static %}
	{% load static %}
{% endblock %}

templates/products/products.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
	<section id="content">
        <div class="container">
             <div class="c-header">
            	<h2>{{title}}</h2>
            </div>

            <div class="action-header palette-theme {{current_theme}} bg clearfix">
	            <div class="ah-label hidden-xs palette-White text">{{title}}</div>

	            <div class="ah-search">
	            	<form method="get" action="{% url 'products:products' %}" class="ahs-input">
	                    <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

	                    <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
	                    <input type="submit" class="hidden" />
	                </form>
	            </div>

	            <ul class="ah-actions actions a-alt">
	                <li>
	                    <a href="" class="ah-search-trigger" data-ma-action="ah-search-open">
	                        <i class="zmdi zmdi-search"></i>
	                    </a>
	                </li>
	                <li>
	                    <a title="Filter" class="filter_button" href="">
	                        <i class="zmdi zmdi-filter-list"></i>
	                    </a>
	                </li>
	                <li>
                        <a title="Create Product" href="{% url 'products:create' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
	                {% if instances %}
    	                <li>
    	                    <a title="Select All" class="check_all" href="">
    	                        <i class="zmdi zmdi-select-all"></i>
    	                    </a>
    	                </li>
	                {% endif %}
	            </ul>
	        </div>

            <div class="card">

				{% if instances %}

                <div class="table-responsive">
                    <table id="data-table-basic" class="table table-striped table-vmiddle">
                        <thead>
                            <tr>
                            	<th style="width:20px;"></th>
                                <th data-column-id="id" data-type="numeric">ID</th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Stock</th>
                                <th data-column-id="action">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% load el_pagination_tags %}
							{% paginate 10 instances %}
                        	{% for instance in instances %}
                            <tr class="check_items_row">
                            	<td style="width:20px;">
                            		<div class="checkbox lgi-checkbox m-t-5">
			                            <label>
			                                <input class="check check_item" type="checkbox" value="{{instance.pk}}" name="delete_item">
			                                <i class="input-helper"></i>
			                            </label>
			                        </div>
                            	</td>
                                <td><a href="{% url 'products:product' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                                <td>{{instance.name}}</td>
                                <td>{{instance.price}}</td>
                                 <td>{{instance.stock}}</td>
                                <td>
                                	<a href="{% url 'products:product' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                                	<a href="{% url 'products:edit' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                	<a data-id="{{instance.pk}}" href="{% url 'products:delete' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!--pagination -->
                <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                	{% get_pages %}
                	<div class="row">
                		<div class="col-sm-6">
                			<div class="pagination">
                				{% show_pages %}
                			</div>
                		</div>
                		<div class="col-sm-6 infoBar">
                			<div class="infos">
                				Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                			</div>
                		</div>
                	</div>
                </div>
                <!--pagination-->
                {% else %}
                	{% include 'includes/not_found.html' %}
                {% endif %}
            </div>

        </div>
    </section>
{% endblock %}

{% block filter_box %}
<div class="filter-box">
	 <form method="get" action="{% url 'products:products' %}">
	 	<div class="card">
			<div class="card-header">
		        <h2>Filter <small></small></h2>
		        <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i> Back</span>
		    </div>

			<div class="card-body card-padding">
			 	<div class="form-group fg-line">
		            <label>Query</label>
		            <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
		        </div>

		         <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
		    </div>
		 </div>
	 </form>
</div>
{% endblock %}

{% block static %}
	{% load static %}
{% endblock %}