api/v1/sales/urls.py
from django.conf.urls import url
import views


urlpatterns = [
    url(r'^$', views.sales, name="sales"),
    url(r'^sale/(?P<pk>.*)/$', views.sale, name="sale"),
]

customers/urls.py
from django.conf.urls import url
import views
from customers.views import CustomerAutocomplete


urlpatterns = [
	url(r'^customer-autocomplete/$',CustomerAutocomplete.as_view(),name='customer_autocomplete'),
	url(r'^create/$', views.create, name="create"),
	url(r'^edit/(?P<pk>.*)/$', views.edit, name="edit"),
	url(r'^$', views.customers, name="customers"),
	url(r'^customer/(?P<pk>.*)/$', views.customer, name="customer"),
	url(r'^delete/(?P<pk>.*)/$', views.delete, name="delete"),

	url(r'^get-customer/$', views.get_customer, name="get-customer"),
]

products/urls.py
from django.conf.urls import url
import views
from products.views import ProductAutocomplete


urlpatterns = [
	url(r'^product-autocomplete/$',ProductAutocomplete.as_view(),name='product_autocomplete'),
	url(r'^create/$', views.create, name="create"),
	url(r'^edit/(?P<pk>.*)/$', views.edit, name="edit"),
	url(r'^$', views.products, name="products"),
	url(r'^product/(?P<pk>.*)/$', views.product, name="product"),
	url(r'^delete/(?P<pk>.*)/$', views.delete, name="delete"),
	url(r'^get-product/$', views.get_product, name="get_product"),
]

sales/urls.py
from django.conf.urls import url
import views


urlpatterns = [
	url(r'^create/$', views.create, name="create"),
	url(r'^edit/(?P<pk>.*)/$', views.edit, name="edit"),
	url(r'^$', views.sales, name="sales"),
	url(r'^sale/(?P<pk>.*)/$', views.sale, name="sale"),
	url(r'^delete/(?P<pk>.*)/$', views.delete, name="delete"),
]

tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^api/v1/customers/', include('api.v1.customers.urls', namespace='api_v1_customers')),
    url(r'^api/v1/sales/', include('api.v1.sales.urls', namespace='api_v1_sales')),
    url(r'^api/v1/auth/', include('api.v1.authentication.urls', namespace='api_v1_authentication')),

    url(r'^$',general_views.app,name='app'),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),

    url(r'^app/customers/', include('customers.urls', namespace="customers")),
    url(r'^app/products/', include('products.urls', namespace="products")),
    url(r'^app/sales/', include('sales.urls', namespace="sales")),
    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^app/users/', include('users.urls', namespace="users")),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

sales/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MinValueValidator
from decimal import Decimal
from main.models import BaseModel


class Sale(BaseModel):
    customer = models.ForeignKey('customers.Customer', limit_choices_to={'is_deleted': False})
    date = models.DateField()
    subtotal = models.DecimalField(default=0.00, decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])
    discount = models.DecimalField(default=0.00, decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])
    total = models.DecimalField(default=0.00, decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])

    class Meta:
        db_table = 'sales_sale'
        verbose_name = '_(sale)'
        verbose_name_plural = '_(sale)'
        ordering = ('-date',)

    def __unicode__(self):
        return str(self.auto_id)


class SaleItem(models.Model):
    sale = models.ForeignKey('sales.Sale')
    product = models.ForeignKey('products.Product', limit_choices_to={'is_deleted': False})
    qty = models.DecimalField(default=0.00, decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))]) 

    class Meta:
        db_table = 'sales_sale item'
        verbose_name = '_(sale item)'
        verbose_name_plural = '_(sale items)'
        ordering = ('sale',)

    def subtotal(self):
        return self.qty * self.product.price

    def __unicode__(self):
        return str(self.sale.auto_id)

sales/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.forms.widgets import TextInput, Textarea, Select
from sales.models import Sale, SaleItem
from dal import autocomplete


class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        exclude = ['auto_id', 'creator', 'updator', 'is_deleted', 'subtotal', 'total']
        widgets = {
            'customer': autocomplete.ModelSelect2(url='customers:customer_autocomplete',attrs={'data-placeholder': 'Customer','data-minimum-input-length': 1},),
            'date': TextInput(attrs={'class': 'required date-picker form-control', 'placeholder': 'Date'}),
            'discount': TextInput(attrs={'class': 'form-control', 'placeholder': 'Discount'}),
        }
        error_messages = {
            'customer' : {
                'required' : _("Customer field is required."),
            },
            'date' : {
                'required' : _("Date field is required."),
            },
            'discount' : {
                'required' : _("Discount field is required."),
            }
        }


class SaleItemForm(forms.ModelForm):
    class Meta:
        model = SaleItem
        exclude = ['sale']
        widgets = {
            'product': autocomplete.ModelSelect2(url='products:product_autocomplete',attrs={'data-placeholder': 'Product','data-minimum-input-length': 1},),
            'qty': TextInput(attrs={'class': 'form-control', 'placeholder': 'Quantity'}),

        }
        error_messages = {
            'product' : {
                'required' : _("Product field is required."),
            },
            'qty' : {
                'required' : _("Quantity field is required."),
            }
        }

api/v1/sales/views.py
from sales.models import Sale
from rest_framework.renderers import JSONRenderer
from rest_framework.decorators import api_view, permission_classes, renderer_classes
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from api.v1.sales.serializers import SaleSerializer
from rest_framework import status


@api_view(['GET'])
@permission_classes((IsAuthenticated,))
@renderer_classes((JSONRenderer,))
def sales(request):
    instances = Sale.objects.filter(is_deleted=False)
    serialized = SaleSerializer(instances, many=True, context={'request': request})

    response_data = {
        'StatusCode': 6000,
        'data': serialized.data
    }
    return Response(response_data, status=status.HTTP_200_OK)


@api_view(['GET'])
@permission_classes((IsAuthenticated,))
@renderer_classes((JSONRenderer,))
def sale(request, pk):
    instance = None
    if Sale.objects.filter(is_deleted=False, pk=pk).exists():
        instance = Sale.objects.get(is_deleted=False, pk=pk)

    if instance:
        serialized = SaleSerializer(instance, context={'request': request})

        response_data = {
            'StatusCode': 6000,
            'data': serialized.data
        }
    else:
        response_data = {
            'StatusCode': 6001,
            'message': 'Sale not found.'
        }
    return Response(response_data, status=status.HTTP_200_OK)

sales/views.py
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect, HttpResponse
from main.functions import get_auto_id, get_a_id, generate_form_errors
from django.forms import formset_factory, inlineformset_factory
from django.forms.widgets import TextInput, Textarea, Select
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import json
import datetime
from sales.forms import SaleForm, SaleItemForm
from sales.models import Sale, SaleItem
from products.functions import update_stock
from products.models import Product
from products.views import autocomplete


@login_required
def create(request):
    SaleItemFormset = formset_factory(SaleItemForm, extra=1)
    if request.method == 'POST':
        form = SaleForm(request.POST)
        sale_item_formset = SaleItemFormset(request.POST, prefix='sale_item_formset')
        if form.is_valid() and sale_item_formset.is_valid():

            # Creating Sale Item Objects for finding duplicate product entry
            items = {}
            for f in sale_item_formset:  
                product = f.cleaned_data['product']
                qty = f.cleaned_data['qty']
                if str(product.pk) in items:
                    q = items[str(product.pk)]["qty"]
                    items[str(product.pk)]["qty"] = q + qty
                else:
                    dic = {
                        "qty" : qty,
                    }
                    items[str(product.pk)] = dic 

            # Checking the stock available for this product
            stock_ok = True
            error_message = ''
            for key, value in items.items():
                product = Product.objects.get(pk=key)
                stock = product.stock
                qty = value['qty']
                if qty > stock:
                    stock_ok = False
                    error_message += "{} has only {} in stock, You entered {} qty".format(product.name,str(stock),str(qty))

            if stock_ok:
                discount = form.cleaned_data['discount']
                data = form.save(commit=False)
                data.creator = request.user
                data.updator = request.user
                data.auto_id = get_auto_id(Sale)
                data.save()

                subtotal = 0
                for key, value in items.items():
                    product = Product.objects.get(pk=key)
                    qty = value["qty"]
                    price = product.price
                    sub = (qty * price)
                    subtotal += sub 
                    
                    SaleItem(
                        sale = data,
                        product = product,
                        qty = qty
                    ).save()

                    update_stock(product.pk, qty, 'decrease')

                total = subtotal - discount
                data.subtotal = subtotal
                data.total = total
                data.save()
                    
                response_data = {
                    "status" : "true",
                    "title" : "Successfully Created",
                    "message" : "Sale Successfully Created.",
                    "redirect" : "true",
                    "redirect_url" : reverse('sales:sale',kwargs={'pk':data.pk})
                }
            else:
                response_data = {
                    "status" : "false",
                    "stable" : "true",
                    "title" : "Out of Stock",
                    "message" : error_message
                }
        else:
            message = generate_form_errors(form,formset=False)     
            message += generate_form_errors(sale_item_formset,formset=True)
            response_data = {
                "status" : "false",
                "stable" : "true",
                "title" : "Form validation error",
                "message" : message
            }  
            
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        form = SaleForm()
        sale_item_formset = SaleItemFormset(prefix='sale_item_formset')
        context = {
            'title': 'Create Sale',
            'form': form,
            'sale_item_formset': sale_item_formset,
            'redirect': True,
            'url': reverse('sales:create'),

            "is_need_select_picker" : True,
            "is_need_popup_box" : True,
            "is_need_custom_scroll_bar" : True,
            "is_need_wave_effect" : True,
            "is_need_bootstrap_growl" : True,
            "is_need_chosen_select" : True,
            "is_need_grid_system" : True,
            "is_need_datetime_picker" : True,
            "is_need_animations": True,
            "is_dashboard" :True
        }
        return render(request, 'sales/entry.html', context)


@login_required
def edit(request, pk):
    instance = get_object_or_404(Sale.objects.filter(pk=pk))
    if SaleItem.objects.filter(sale=instance).exists():
        extra = 0
    else:
        extra = 1

    SaleItemFormset = inlineformset_factory(
            Sale,
            SaleItem,
            can_delete = True,
            extra = extra,
            exclude = ('sale',),
            widgets = {
            'product': autocomplete.ModelSelect2(url='products:product_autocomplete',attrs={'data-placeholder': 'Product','data-minimum-input-length': 1},),
            'qty': TextInput(attrs={'class': 'form-control', 'placeholder': 'Quantity'}),
            }
        )

    if request.method == 'POST':
        form = SaleForm(request.POST, instance=instance)
        sale_item_formset = SaleItemFormset(request.POST, prefix='sale_item_formset', instance=instance)
        if form.is_valid() and sale_item_formset.is_valid():

            # Creating Sale Item Objects for finding duplicate product entry
            items = {}
            for f in sale_item_formset:  
                product = f.cleaned_data['product']
                qty = f.cleaned_data['qty']
                if str(product.pk) in items:
                    q = items[str(product.pk)]["qty"]
                    items[str(product.pk)]["qty"] = q + qty
                else:
                    dic = {
                        "qty" : qty,
                    }
                    items[str(product.pk)] = dic 

            # Checking the stock available for this product
            stock_ok = True
            error_message = ''
            for key, value in items.items():
                product = Product.objects.get(pk=key)
                prev_qty = 0
                if SaleItem.objects.filter(sale=instance, product=product).exists():
                    prev_qty = SaleItem.objects.get(sale=instance, product=product).qty   
                stock = product.stock + prev_qty
                qty = value['qty']
                if qty > stock:
                    stock_ok = False
                    error_message += "{} has only {} in stock, You entered {} qty".format(product.name,str(stock),str(qty))

            if stock_ok:
                discount = form.cleaned_data['discount']
                data = form.save(commit=False)
                data.updator = request.user
                data.date_updated = datetime.datetime.now()
                data.save()

                #delete previous items and update stock
                previous_sale_items = SaleItem.objects.filter(sale=instance)
                for p in previous_sale_items:
                    prev_qty = p.qty
                    update_stock(p.product.pk, prev_qty, 'increase')
                previous_sale_items.delete()

                #save items
                subtotal = 0
                for key, value in items.items():
                    product = Product.objects.get(pk=key)
                    qty = value["qty"]
                    price = product.price
                    sub = (qty * price)
                    subtotal += sub 
                    
                    SaleItem(
                        sale = data,
                        product = product,
                        qty = qty
                    ).save()

                    update_stock(product.pk, qty, 'decrease')

                total = subtotal - discount
                data.subtotal = subtotal
                data.total = total
                data.save()
                    
                response_data = {
                    "status" : "true",
                    "title" : "Successfully Updated",
                    "message" : "Sale Successfully Updated.",
                    "redirect" : "true",
                    "redirect_url" : reverse('sales:sale',kwargs={'pk':data.pk})
                }
            else:
                response_data = {
                    "status" : "false",
                    "stable" : "true",
                    "title" : "Out of Stock",
                    "message" : error_message
                }
        else:
            message = generate_form_errors(form,formset=False)     
            message += generate_form_errors(sale_item_formset,formset=True)
            response_data = {
                "status" : "false",
                "stable" : "true",
                "title" : "Form validation error",
                "message" : message
            }  
            
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')


    else:
        form = SaleForm(instance=instance)
        sale_item_formset = SaleItemFormset(prefix='sale_item_formset', instance=instance)
        context = {
            'title': 'Edit Sale',
            'form': form,
            'sale_item_formset': sale_item_formset,
            'redirect': True,
            'url': reverse('sales:edit', kwargs={'pk':instance.pk}),

            "is_need_select_picker" : True,
            "is_need_popup_box" : True,

templates/sales/entry.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
	<section id="content">
        <div class="container">
            <div class="c-header">
                <h2>{{title}}</h2>
            </div>

			<div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{title}}</div>

                <div class="ah-search">
	            	<form method="get" action="{% url 'sales:sales' %}">
	                    <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

	                    <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
	                    <input type="submit" class="hidden" />
	                </form>
	            </div>

                <ul class="ah-actions actions a-alt">
                    <li>
                        <a title="Search" data-ma-action="ah-search-open" class="ah-search-trigger" href="">
                            <i class="zmdi zmdi-search"></i>
                        </a>
                    </li>
                    {% if instance %}
                    <li>
                        <a title="Create Product" href="{% url 'sales:create' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
                    <li>
                        <a title="View Product" href="{% url 'sales:sale' pk=instance.pk %}">
                            <i class="zmdi zmdi-eye"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Delete Product" data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'sales:delete' pk=instance.pk %}" class="action-button redirect">
                            <i class="zmdi zmdi-delete"></i>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>

            <form class="ajax reset redirect skip_empty_row not_allowed_without_formset " method="post" action="{{url}}">
                {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="card">
                                <div class="card-body card-padding">
                                    <div class="form-group fg-line">
                                        <label for="{{ form.customer.id_for_label }}">
                                            {{ form.customer.label }}
                                            {% if form.customer.field.required %}
                                                <small class="star">*</small>
                                            {% endif %}

                                            {% if form.customer.help_text %}
                                                <span data-original-title="Field Info" title="" data-content="{{ form.customer.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline"></span>
                                            {% endif %}
                                        </label>
                                        {{ form.customer }}

                                        {% if form.customer.errors %}
                                            <label class="error">{{ form.customer.errors.as_text }}</label>
                                        {% endif %}
                                    </div>

                                    <div class="form-group fg-line">
                                        <label for="{{ form.date.id_for_label }}">
                                            {{ form.date.label }}
                                            {% if form.date.field.required %}
                                                <small class="star">*</small>
                                            {% endif %}

                                            {% if form.date.help_text %}
                                                <span data-original-title="Field Info" title="" data-content="{{ form.date.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline"></span>
                                            {% endif %}
                                        </label>
                                        {% if is_create_page %}
                                            <input id="{{ form.date.id_for_label }}" type="text" class="required form-control date-picker"  name="{{form.date.html_name}}" placeholder="Enter date" value="{% now "m-d-Y" %}">
                                        {% else %}
                                            <input id="{{ form.date.id_for_label }}" type="text" class="required form-control date-picker"  name="{{form.date.html_name}}" placeholder="Enter date" value="{{ form.date.value|date:'m-d-Y' }}">
                                        {% endif %}
                                        {% if form.date.errors %}
                                            <label class="error">{{ form.date.errors.as_text }}</label>
                                        {% endif %}
                                    </div>

                                    <div class="form-group fg-line">
                                        <label for="{{ form.discount.id_for_label }}">
                                            {{ form.discount.label }}
                                            {% if form.discount.field.required %}
                                                <small class="star">*</small>
                                            {% endif %}

                                            {% if form.discount.help_text %}
                                                <span data-original-title="Field Info" title="" data-content="{{ form.discount.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline"></span>
                                            {% endif %}
                                        </label>
                                        {{ form.discount }}

                                        {% if form.discount.errors %}
                                            <label class="error">{{ form.discount.errors.as_text }}</label>
                                        {% endif %}
                                    </div>
                                    <div class="form-group fg-line">
                                        <label for="customer-email">Customer Email</label>
                                        <input class="form-control" type="email" name="" id="customer-email" placeholder="Email id" value="" disabled />
                                    </div>
                                    <div class="form-group fg-line">
                                        <label for="customer-phone">Customer Phone</label>
                                        <input class="form-control" type="text" name="" id="customer-phone" placeholder="Phone" value="" disabled />
                                    </div>
                                    <div class="form-group fg-line media m-b-0">
                                        <label for="customer-address">Customer Address</label>
                                        <input class="form-control" type="textarea" name="" id="customer-phone" placeholder="Phone" value="" disabled />
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="card sale-item-card">
                                <div class="table-responsive card-body add_item_container sale_item_formset">
                                    <table id="data-table-basic" class="table table-striped table-vmiddle">
                                        <thead>
                                            <tr>
                                                <th data-column-id="product">Product</th>
                                                <th data-column-id="stock">Stock</th>
                                                <th data-column-id="qty">Qty</th>
                                                <th class="one"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for item in sale_item_formset.forms %}               
                                            <tr class="form_set_row">
                                                <td style="width:30%;" >
                                                    {{ item.id }}
                                                    <span class="sale_item p-relative">                  
                                                        {{ item.product }}
                                                    </span>
                                                </td>
                                                <td style="width:30%;" >
                                                    {{ item.id }}
                                                    <span class="sale_item_stock p-relative">
                                                        <input class="form-control" type="text" value="0" name="" disabled="" />             
                                                    </span>
                                                </td>
                                                <td>
                                                    <span class="sale_item_qty check_empty p-relative">
                                                        {{ item.qty }}
                                                    </span>
                                                </td>
                                                <td class="one">{% if form.instance.pk %}{{ form.DELETE }}{% endif %}</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                    {{ sale_item_formset.management_form }}
                                </div> 
                            </div>
                        </div>

                    </div>
                     <div>
                        <button type="submit" class="btn btn-info waves-effect">Submit</button>
                    </div>
            </form>
        </div>
    </section>
{% endblock %}

{% block static %}
	{% load static %}
    <script type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('input[type=text]').focus(function () {
               $(this).select();
            });

            $('.sale_item_formset table tr.form_set_row').formset({
                prefix: '{{ sale_item_formset.prefix }}',
                formCssClass: 'dynamic-formset1',
                'added' : function (row) {
                    row.find('.sale_item select').val(null).trigger('change');
                    row.find('.select2-selection').click();
                }
            }); 
        });
        $('#id_customer').change(function(){
            var $this = $(this);
            get_customer_data($this);   
        });

        $('.sale_item select').change(function(){
            var $this = $(this);
            get_product_info($this);
        });

        function get_customer_data(element){
            var customer_id = element.val();
            if (customer_id != null && customer_id != ""){
                var url = "{% url 'customers:get-customer' %}";
                $.ajax({
                    type : "GET",
                    url : url,
                    dataType : 'json',
                    data : {
                        id : customer_id,
                    },
                    success : function(data) {
                        var status = data['status'];
                        if (status == 'true'){
                            var email = data['email'];
                            var phone = data['phone'];
                            var address = data['address'];

                            $("#customer-email").val(email);
                            $("#customer-phone").val(phone);
                            $("#customer-address").val(address);
                        }

                    },
                    error : function(data){
                    }
                }); 
            }
        };

        function get_product_info(selector){
            var product_id = selector.val();
            var parent = selector.parents('tr.form_set_row');
            if (product_id != null && product_id != ''){
                var url = "{% url 'products:get_product' %}"
                $.ajax({
                    type: 'GET',
                    url: url,
                    dataType: 'json',
                    data: {
                        id: product_id,
                    },
                    success : function(data) {
                        var status = data['status'];
                        if (status == 'true') {
                            var stock = data['stock'];
                            parent.find('.sale_item_stock input').val(stock);
                        }
                    },
                    error: function(data) {
                    } 
                });
            }
        }
    </script>
    {{form.media}}
{% endblock %}