products/urls.py
from django.conf.urls import url
import views
from products.views import ProductAutocomplete


urlpatterns = [
	url(r'^product-autocomplete/$',ProductAutocomplete.as_view(),name='product_autocomplete'),
	url(r'^create/$', views.create, name="create"),
	url(r'^edit/(?P<pk>.*)/$', views.edit, name="edit"),
	url(r'^$', views.products, name="products"),
	url(r'^product/(?P<pk>.*)/$', views.product, name="product"),
	url(r'^delete/(?P<pk>.*)/$', views.delete, name="delete"),
	url(r'^get-product/$', views.get_product, name="get_product"),
]

sales/urls.py
from django.conf.urls import url
import views


urlpatterns = [
	url(r'^create/$', views.create, name="create"),
	url(r'^edit/(?P<pk>.*)/$', views.edit, name="edit"),
	url(r'^$', views.sales, name="sales"),
	url(r'^sale/(?P<pk>.*)/$', views.sale, name="sale"),
	url(r'^delete/(?P<pk>.*)/$', views.delete, name="delete"),
]

tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^api/v1/customers/', include('api.v1.customers.urls', namespace='api_v1_customers')),
    url(r'^api/v1/sales/', include('api.v1.sales.urls', namespace='api_v1_sales')),
    url(r'^api/v1/auth/', include('api.v1.authentication.urls', namespace='api_v1_authentication')),

    url(r'^$',general_views.app,name='app'),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),

    url(r'^app/customers/', include('customers.urls', namespace="customers")),
    url(r'^app/products/', include('products.urls', namespace="products")),
    url(r'^app/sales/', include('sales.urls', namespace="sales")),
    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^app/users/', include('users.urls', namespace="users")),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

users/urls.py
from django.conf.urls import url,include
import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    
    url(r'^check-notification/$', views.check_notification, name='check_notification'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notification/delete/(?P<pk>.*)/$', views.delete_notification, name='delete_notification'),
    url(r'^delete-selected-notifications/$', views.delete_selected_notifications, name='delete_selected_notifications'),
    url(r'^notification/read/(?P<pk>.*)/$', views.read_notification, name='read_notification'),
    url(r'^read-selected-notifications/$', views.read_selected_notifications, name='read_selected_notifications'),
    
    url(r'^set-user-timezone/$', views.set_user_timezone, name='set_user_timezone'),
    
    
]

users/forms.py
from registration.forms import RegistrationForm
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.forms.widgets import TextInput


class UserForm(RegistrationForm):
    
    username = forms.CharField(label=_("Username"), 
                               max_length=254,
                               widget=forms.TextInput(
                                    attrs={'placeholder': 'Enter username','class':'required form-control'})
                               )
    email = forms.EmailField(label=_("Email"), 
                             max_length=254,
                             widget=forms.TextInput(
                                attrs={'placeholder': 'Enter email','class':'required form-control'})
                             )
    password1 = forms.CharField(label=_("Password"), 
                               widget=forms.PasswordInput(
                                    attrs={'placeholder': 'Enter password','class':'required form-control'})
                               )
    password2 = forms.CharField(label=_("Repeat Password"), 
                               widget=forms.PasswordInput(
                                    attrs={'placeholder': 'Enter password again','class':'required form-control'})
                               )
    
    bad_domains = ['guerrillamail.com']
    
    def clean_email(self):
        email_domain = self.cleaned_data['email'].split('@')[1]
        if User.objects.filter(email__iexact=self.cleaned_data['email'],is_active=True):
            raise forms.ValidationError(_("This email address is already in use."))        
        elif email_domain in self.bad_domains:
            raise forms.ValidationError(_("Registration using %s email addresses is not allowed. Please supply a different email address." %email_domain))
        return self.cleaned_data['email']
    
    min_password_length = 6
    
    def clean_password1(self):
        password1 = self.cleaned_data.get('password1', '')
        if len(password1) < self.min_password_length:
            raise forms.ValidationError("Password must have at least %i characters" % self.min_password_length)
        else:
            return password1
    
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2
        
    min_username_length = 6

    def clean_username(self):
        username = self.cleaned_data['username']
        existing = User.objects.filter(username__iexact=self.cleaned_data['username'])
        if existing.exists():
            raise forms.ValidationError(_("A user with that username already exists."))
        elif len(username) < self.min_username_length:
            raise forms.ValidationError("Username must have at least %i characters" % self.min_password_length)
        else:
            return self.cleaned_data['username']  


class RegForm(RegistrationForm):

    bad_domains = ['guerrillamail.com']

    def clean_email(self):
        email_domain = self.cleaned_data['email'].split('@')[1]
        if User.objects.filter(email__iexact=self.cleaned_data['email']):
            raise forms.ValidationError(_("This email address is already in use."))
        elif email_domain in self.bad_domains:
            raise forms.ValidationError(_("Registration using %s email addresses is not allowed. Please supply a different email address." %email_domain))
        return self.cleaned_data['email']

    min_password_length = 6

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1', '')
        if len(password1) < self.min_password_length:
            raise forms.ValidationError("Password must have at least %i characters" % self.min_password_length)
        else:
            return password1

    min_username_length = 5

    def clean_username(self):
        username = self.cleaned_data['username']
        existing = User.objects.filter(username__iexact=self.cleaned_data['username'])
        if existing.exists():
            raise forms.ValidationError(_("A user with that username already exists."))
        elif len(username) < self.min_username_length:
            raise forms.ValidationError("Username must have at least %i characters" % self.min_password_length)
        else:
            return self.cleaned_data['username']

users/views.py
from django.http.response import HttpResponse
import json
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect, HttpResponse
import json
from users.forms import UserForm
from users.models import Notification, Permission
from django.views.decorators.http import require_GET, require_POST
from django.contrib.auth.decorators import login_required
from main.decorators import ajax_required,check_mode
from django.shortcuts import resolve_url, render, get_object_or_404
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.tokens import default_token_generator
from django.template.response import TemplateResponse
from django.forms.models import modelformset_factory
from django.contrib.auth.models import User, Group
from django.core.mail import send_mail
from users.models import Notification
from main.functions import get_auto_id,get_a_id,generate_form_errors
from main.decorators import check_mode,ajax_required
from django.contrib.auth.forms import PasswordChangeForm
from django.db.models import Q


@check_mode
@login_required
def dashboard(request):
    return HttpResponseRedirect(reverse('app'))


@check_mode
@login_required
@ajax_required
@require_GET
def check_notification(request):
    current_shop = get_current_shop(request)
    user = request.user
    count = Notification.objects.filter(user=user,is_read=False,is_active=True,shop=current_shop).count()
    return HttpResponse(json.dumps(count), content_type='application/javascript')


@check_mode
@login_required
def notifications(request):
    title = "Notifications"
    current_shop = get_current_shop(request)
    instances = Notification.objects.filter(user=request.user,is_deleted=False,is_active=True,shop=current_shop)

    query = request.GET.get("q")
    if query:
        instances = instances.filter(Q(subject__name__icontains=query) | Q(product__name__icontains=query))
        title = "Notifications - %s" %query

    context = {
        'title' : title,
        "instances" : instances,
        "is_need_select_picker": True,
        "is_need_popup_box" : True,

        "is_need_select_picker" : True,
        "is_need_popup_box" : True,
        "is_need_custom_scroll_bar" : True,
        "is_need_wave_effect" : True,
        "is_need_bootstrap_growl" : True,
        "is_need_chosen_select" : True,
        "is_need_grid_system" : True,
        "is_need_datetime_picker" : True,
        "is_need_animations": True,
    }
    return render(request,"users/notifications.html",context)


@check_mode
@login_required
def delete_notification(request,pk):
    Notification.objects.filter(pk=pk,user=request.user).update(is_deleted=True,is_read=True)

    response_data = {
        "status" : "true",
        "title" : "Successfully Deleted",
        "message" : "Notification Successfully Deleted.",
        "redirect" : "true",
        "redirect_url" : reverse('users:notifications')
    }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@check_mode
@login_required
def delete_selected_notifications(request):
    pks = request.GET.get('pk')
    if pks:
        pks = pks[:-1]

        pks = pks.split(',')
        for pk in pks:
            Notification.objects.filter(pk=pk,user=request.user).update(is_deleted=True,is_read=True)

        response_data = {
            "status" : "true",
            "title" : "Successfully Deleted",
            "message" : "Selected Notification(s) Successfully Deleted.",
            "redirect" : "true",
            "redirect_url" : reverse('users:notifications')
        }
    else:
        response_data = {
            "status" : "false",
            "title" : "Nothing selected",
            "message" : "Please select some items first.",
        }

    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@check_mode
@login_required
def read_selected_notifications(request):
    pks = request.GET.get('pk')
    if pks:
        pks = pks[:-1]

        pks = pks.split(',')
        for pk in pks:
            Notification.objects.filter(pk=pk,user=request.user).update(is_deleted=True,is_read=True)

        response_data = {
            "status" : "true",
            "title" : "Successfully marked as read",
            "message" : "Selected notification(s) successfully marked as read.",
            "redirect" : "true",
            "redirect_url" : reverse('users:notifications')
        }
    else:
        response_data = {
            "status" : "false",
            "title" : "Nothing selected",
            "message" : "Please select some items first.",
        }

    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@check_mode
@login_required
def read_notification(request,pk):
    Notification.objects.filter(pk=pk,user=request.user).update(is_read=True)

    response_data = {
        "status" : "true",
        "title" : "Successfully marked as read",
        "message" : "Notification successfully marked as read.",
        "redirect" : "true",
        "redirect_url" : reverse('users:notifications')
    }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@login_required
@ajax_required
@require_GET
def set_user_timezone(request):
    timezone = request.GET.get('timezone')
    request.session["set_user_timezone"] = timezone
    response_data = {}
    response_data['status'] = 'true'
    response_data['title'] = "Success"
    response_data['message'] = 'user timezone set successfully.'
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@check_mode
@login_required
def change_password(request,pk):
    instance = get_object_or_404(User.objects.filter(pk=pk,is_active=True))
    if request.method == "POST":
        response_data = {}
        form = PasswordChangeForm(user=instance, data=request.POST)
        if form.is_valid():
            form.save()

            response_data = {
                'status' : 'true',
                'title' : "Successfully Changed",
                'redirect' : 'false',
                'message' : "Password Successfully Changed."
            }
        else:
            message = generate_form_errors(form,formset=False)

            response_data = {
                'status' : 'false',
                'stable' : 'true',
                'title' : "Form validation error",
                "message" : message,
            }
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:
        title = "Change Password"
        change_password_form = PasswordChangeForm(user=instance)
        context = {
            "change_password_form" : change_password_form,
            "title" : title,
            "instance" : instance,

            "is_need_popup_box": True,
            "is_need_custom_scroll_bar": True,
            "is_need_wave_effect": True,
            "is_need_bootstrap_growl": True,
            "is_need_animations": True,
            "is_need_grid_system": True,
            "is_need_select_picker": True,
            "is_need_datetime_picker" : True
        }
        return render(request, 'users/change_password.html', context)


@ajax_required
@login_required
def revoke_access(request,pk):
    current_shop = get_current_shop(request)
    instance = get_object_or_404(Staff.objects.filter(pk=pk,is_deleted=False,shop=current_shop))

    User.objects.filter(pk=instance.user.pk).update(is_active=False,
                                                    username=instance.user.username + "_deleted"+ str(instance.user.id) ,
                                                    email=instance.user.email + "_deleted")
    #unset user
    Staff.objects.filter(pk=pk).update(user=None)

    instance.permissions.clear()

    response_data = {
        "status" : "true",
        "title" : "Access Revoked.",
        "message" : "Access Revoked Successfully.",
        "redirect" : "true",
        "redirect_url" : reverse('staffs:staff', kwargs = {'pk' : pk})
    }

    return HttpResponse(json.dumps(response_data), content_type='application/javascript')

templates/users/change_password.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
 			<section id="content">
                <div class="container">
                    <div class="c-header">
                        <h2>{{title}} : {{instance.username}}</h2>
                    </div> 
                     <div class="card col-sm-5">
                        <form action="{% url 'users:change_password' pk=instance.pk %}" class="ajax  reset {% if redirect %}redirect{% endif %}" method="post" >
                        	{% csrf_token %}
                            <div class="card-body card-padding">
                                   {% include 'includes/form.html' with form=change_password_form %}
                                <div class="form-group">
                                    <div class="m-t-20">
									    <button type="submit" class="btn btn-info waves-effect">Submit</button>
									</div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
{% endblock %}

{% block static %}
	{% load static %}
    <script>
    $(document).ready(function(){
        $('input[type="password"]').addClass("form-control");
    })
    </script>
{% endblock %}

templates/users/notifications.html
{% extends "base.html" %}
{% load i18n %}

{% load users_template_tags %}
{% load tz %}
{% block content %}
	<section id="content">
        <div class="container">
            <div class="c-header">
                <h2>{{title}}</h2>
            </div>

            <div class="card">
            	
            	<div class="action-header palette-theme {{current_theme}} bg clearfix">
                    <div class="ah-label hidden-xs palette-White text">Recent Notifications</div>

                    <div class="ah-search">
                    	<form method="get" action="{% url 'users:notifications' %}">
	                        <input name="q" type="text" placeholder="Start typing..." class="ahs-input">
	
	                        <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
	                        <input type="submit" class="hidden" />
                        </form>
                    </div>

                    <ul class="ah-actions actions a-alt">
                        <li>
                            <a href="" class="ah-search-trigger" data-ma-action="ah-search-open">
                                <i class="zmdi zmdi-search"></i>
                            </a>
                        </li>
                        
                        {% if instances %}

                        <li>
                            <a class="check_all" href="">
                                <i class="zmdi zmdi-select-all"></i>
                            </a>
                        </li>
                        
                        <li>
                            <a title="Delete selected items" data-id="" href="{% url 'users:delete_selected_notifications' %}" data-text="{{confirm_delete_selected_message}}" data-title="Are you sure?" class="action-button reload selected-items-button">
                                <i class="zmdi zmdi-delete"></i>
                            </a>
                        </li>
                        
                        <li>
                            <a title="Mark as read" data-id="" href="{% url 'users:read_selected_notifications' %}" data-text="{{confirm_read_selected_message}}" data-title="Are you sure?" class="action-button selected-items-button">
                                <i class="zmdi zmdi-check-all"></i>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                    
                </div>
            	
            	{% if instances %}

                <div class="list-group lg-alt lg-even-black">
                	
                	{% load el_pagination_tags %}
					{% paginate 21 instances %}
                	{% for notification in instances %}
                	
                    <div class="list-group-item check_items_row media">
                        <div class="checkbox pull-left lgi-checkbox">
                            <label>
                                <input class="check check_item" type="checkbox" value="{{notification.pk}}" name="delete_item">
                                <i class="input-helper"></i>
                            </label>
                        </div>

                        <div class="pull-left">
                            
                        	{% if notification.subject.code == "low_stock_notification" %}
                        	<div class="avatar-char palette-Red bg">
                        		<i class="zmdi zmdi-alert-circle-o"></i>
                            </div>
                        	{% elif notification.subject.code == "task_assigned" %}
                        	<div class="avatar-char palette-Amber bg">
                        		<i class="zmdi zmdi-money-off"></i>
                        	 </div>
                        	
                        	{% elif notification.subject.code == "expiry_notification" %}
                        	<div class="avatar-char palette-Red bg">
                        		<i class="zmdi zmdi-money-off"></i>
                        	</div>
                        	
                        	{% endif %}

                        </div>

                        <div class="pull-right">
                            <ul class="actions">
                                <li class="dropdown">
                                    <a href="" data-toggle="dropdown" aria-expanded="false">
                                        <i class="zmdi zmdi-more-vert"></i>
                                    </a>

                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li>
                                            <a data-id="{{notification.pk}}" href="{% url 'users:delete_notification' pk=notification.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button reload">Delete</a>
                                        </li>
                                        <li>
                                            <a data-id="{{notification.pk}}" href="{% url 'users:read_notification' pk=notification.pk %}" data-text="{{confirm_read_message}}" data-title="Are you sure?" class="action-button reload">Mark as read</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
						{% if notification.subject.code == "low_stock_notification" %}
                        <div class="media-body">
                            <div class="lgi-heading">{{notification.subject}}</div>
                            <small class="lgi-text">Only {{notification.product.stock}} item in stock of {{notification.product}} remaining ({{notification.product.shop}}).</small>
                        </div>
                        
                        {% elif notification.subject.code == "task_assigned" %}
                        <div class="media-body">
                            <div class="lgi-heading">{{notification.subject}}</div>
                            <small class="lgi-text">New Task Assinged to</small>
                        </div>
                        
                        {% elif notification.subject.code == "expiry_notification" %}
                        <div class="media-body">
                            <div class="lgi-heading">{{notification.subject}}</div>
                            <small class="lgi-text"><a href="{% url 'products:product' pk=notification.product.pk %}">{{notification.product.name}}</a> will expire in {{notification.expiry_date.expiry_date|date:'d M Y'|default:""}} </small>
                        </div>
                        
                        {% endif %}
                        
                    </div>
                    {% endfor %}
                    
                </div>

                <!--pagination -->
                <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                	{% get_pages %}
                	<div class="row">
                		<div class="col-sm-6">
                			<div class="pagination">
                				{% show_pages %}
                			</div>
                		</div>
                		<div class="col-sm-6 infoBar">
                			<div class="infos">
                				Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                			</div>
                		</div>
                	</div>
                </div>   
                <!--pagination-->
                
                
                {% else %}
                	{% include 'includes/not_found.html' %}
                {% endif %}   
            </div>
        </div>
    </section>
{% endblock %}

{% block static %}
	{% load static %}
{% endblock %}

templates/users/user.html
{% extends "base.html" %}
{% load i18n %}

{% block title %} {{title}} {% endblock %}

{% block content %}
<section id="content">
    <div class="container">
        <div class="c-header">
            <h2>{{title}}</h2>
        </div>
        <div class="action-header palette-theme {{current_theme}} bg clearfix">
            <div class="ah-label hidden-xs palette-White text">{{instance.username}}</div>

            <div class="ah-search">
            	<form method="get" action="{% url 'users:users' %}">
                    <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

                    <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                    <input type="submit" class="hidden" />
                </form>
            </div>

            <ul class="ah-actions actions a-alt">
                {% if  is_superuser or 'can_change_password' in user_instance.permissionlist %}
                <li>
                    <a title="Change Password" href="{% url 'users:change_password' pk=instance.pk %}"><i class="zmdi zmdi-key"></i></a>
                </li>
                {% endif %}
                {% if  is_superuser or 'can_change_user_permissions' in user_instance.permissionlist %}
                 <li>
                    <a title="Change Permissions" href="{% url 'users:change_permissions' pk=instance.pk %}"><i class="zmdi zmdi-layers"></i></a>
                </li>
                {% endif %}
                {% if  is_superuser or 'can_delete_user' in user_instance.permissionlist %}
                <li>
                    <a title="Delete User" data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'users:delete_user' pk=instance.pk %}" class="action-button redirect"><i class="zmdi zmdi-delete"></i></a>
                </li>  
                {% endif %}    
            </ul>
       	 </div>
        <div id="c-grid" class="clearfix" data-columns="2">
            <div class="card">
                <div class="card-header">
                    <h2>Basic Info <small></small></h2>
                </div>

                <div class="card-body">
                    <div class="list-group lg-alt c-overflow">
                    	
                        <div class="list-group-item media">

                            <div class="media-body">
                                <div class="lgi-heading">User Name</div>
                                <small class="lgi-text">{{instance.username}}</small>
                            </div>
                        </div>
                        
                        <div class="list-group-item media">

                            <div class="media-body">
                                <div class="lgi-heading">Email</div>
                                <small class="lgi-text">{{instance.email}}</small>
                            </div>
                        </div>
                        <div class="list-group-item media">

                            <div class="media-body">
                                <div class="lgi-heading">Staff</div>
                                <small class="lgi-text">{{instance.staff.first_name}}</small>
                            </div>
                        </div>
					</div>
				</div>
            </div> 
        </div>       
   </div>
</section>
{% endblock %}

{% block right_menu %}
	
{% endblock %}

{% block static %}
	{% load static %}
{% endblock %}

templates/users/user_timezone_set.html
{% load static %}
{% if not user_session_ok %}
	<script type="text/javascript" src="{% static 'js/jstz.js' %}"></script>
	<script>
		$(document).ready(function(){
			 var timezone = jstz.determine();
			 var timezone_name = timezone.name();
			 $.ajax({
			 	url : "{% url 'users:set_user_timezone' %}",
			 	action : "GET",
			 	data : {
			 		timezone : timezone_name
			 	},
			 	success : function(data){
			 		
			 	},
			 	error : function(data){
			 		
			 	}
			 });
		});
	</script>
{% endif %}